package ngap

// IntiatingMessage Value Present
const (
	IntiatingMessageValuePresentNothing int = iota
	IntiatingMessageValuePresentAMFConfiuraionUpdate
	IntiatingMessageValuePresentHandoverCancel
	IntiatingMessageValuePresentHandoverRequired
	IntiatingMessageValuePresentHandoverRequest
	IntiatingMessageValuePresentInitialContextSetupRequest
	IntiatingMessageValuePresentNGReset
	IntiatingMessageValuePresentNGSetupRequest
	IntiatingMessageValuePresentPathSwitchRequest
	IntiatingMessageValuePresentPDUSessionResourceModifyRequest
	IntiatingMessageValuePresentPDUSessionResourceModifyIndication
	IntiatingMessageValuePresentPDUSessionResourceReleaseCommand
	IntiatingMessageValuePresentPDUSessionResourceSetupRequest
	IntiatingMessageValuePresentPWSCancelRequest
	IntiatingMessageValuePresentRANConfigurationUpdate
	IntiatingMessageValuePresentUEContextModificationRequest
	IntiatingMessageValuePresentUEContextReleaseCommand
	IntiatingMessageValuePresentUERadioCapabilityCheckRequest
	IntiatingMessageValuePresentWriteReplaceWarningRequest
	IntiatingMessageValuePresentAMFStatusIndication
	IntiatingMessageValuePresentCellTrafficTrace
	IntiatingMessageValuePresentDeactivateTrace
	IntiatingMessageValuePresentDownlinkNASTransport
	IntiatingMessageValuePresentDownlinkNonUEAssociatedNRPPaTransport
	IntiatingMessageValuePresentDownlinkRANConfigurationTransfer
	IntiatingMessageValuePresentDownlinkRANStatusTransfer
	IntiatingMessageValuePresentDownlinkUEAssociatedNRPPaTransport
	IntiatingMessageValuePresentErrorIndication
	IntiatingMessageValuePresentHandoverNotify
	IntiatingMessageValuePresentInitialUEMessage
	IntiatingMessageValuePresentLocationReport
	IntiatingMessageValuePresentLocationReportingControl
	IntiatingMessageValuePresentLocationReportingFailureIndication
	IntiatingMessageValuePresentNASNonDeliveryIndication
	IntiatingMessageValuePresentPaging
	IntiatingMessageValuePresentPDUSessionResourceNotify
	IntiatingMessageValuePresentPrivateMessage
	IntiatingMessageValuePresentPWSFailureIndication
	IntiatingMessageValuePresentPWSRestartIndication
	IntiatingMessageValuePresentRerouteNASRequest
	IntiatingMessageValuePresentTraceFailureIndication
	IntiatingMessageValuePresentTraceStart
	IntiatingMessageValuePresentUECapabilityInfoIndication
	IntiatingMessageValuePresentUEContextReleaseRequest
	IntiatingMessageValuePresentUETNLABindingReleaseRequest
	IntiatingMessageValuePresentUplinkNASTransport
	IntiatingMessageValuePresentUplinkNonUEAssociatedNRPPaTransport
	IntiatingMessageValuePresentUplinkRANConfigurationTransfer
	IntiatingMessageValuePresentUplinkRANStatusTransfer
	IntiatingMessageValuePresentUplinkUEAssociatedNRPPaTransport
)

// IntiatingMessage Type
type IntiatingMessage struct {
	ProcedureCode ProcedureCode
	Criticality   Criticality
	Value         IntiatingMessageValue `aper:"openType,referenceFieldName:ProcedureCode"`
}

// IntiatingMessageValue OpenType
type IntiatingMessageValue struct {
	Present        int
	NGSetupRequest *NGSetupRequest `aper:"valueExt,referenceFieldValue:21"`
}
