/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package DataRepository

import (
	"github.com/gin-gonic/gin"
	"gofree5gc/lib/http_wrapper"
	"gofree5gc/lib/openapi/models"
	"gofree5gc/src/udr/logger"
	"gofree5gc/src/udr/udr_handler/udr_message"
)

// SubscriptionDataSubscriptions - Subscription data subscriptions
func PostSubscriptionDataSubscriptions(c *gin.Context) {
	var subscriptionDataSubscriptions models.SubscriptionDataSubscriptions
	if err := c.ShouldBindJSON(&subscriptionDataSubscriptions); err != nil {
		logger.DataRepoLog.Panic(err.Error())
	}

	req := http_wrapper.NewRequest(c.Request, subscriptionDataSubscriptions)

	handlerMsg := udr_message.NewHandlerMessage(udr_message.EventPostSubscriptionDataSubscriptions, req)
	udr_message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
