/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ChangeItem struct {
	Op ChangeType `json:"op" yaml:"op" bson:"op" mapstructure:"Op"`
	Path string `json:"path" yaml:"path" bson:"path" mapstructure:"Path"`
	From string `json:"from,omitempty" yaml:"from" bson:"from" mapstructure:"From"`
	OrigValue map[string]interface{} `json:"origValue,omitempty" yaml:"origValue" bson:"origValue" mapstructure:"OrigValue"`
	NewValue map[string]interface{} `json:"newValue,omitempty" yaml:"newValue" bson:"newValue" mapstructure:"NewValue"`
}
