/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package NSSAIAvailability

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"gofree5gc/lib/http_wrapper"
	"gofree5gc/src/nssf/logger"
	"gofree5gc/src/nssf/nssf_handler"
	"gofree5gc/src/nssf/nssf_handler/nssf_message"
)

func ApiSubscriptionIdDocument(c *gin.Context) {
	// Due to conflict of route matching, 'subscriptions' in the route is replaced with the existing wildcard ':nfId'
	nfId := c.Param("nfId")
	if nfId != "subscriptions" {
		c.JSON(http.StatusNotFound, gin.H{})
		logger.Nssaiavailability.Infof("404 Not Found")
		return
	}

	var request interface{}
	req := http_wrapper.NewRequest(c.Request, request)
	req.Params["subscriptionId"] = c.Param("subscriptionId")

	message := nssf_message.NewMessage(nssf_message.NSSAIAvailabilityUnsubscribe, req)

	nssf_handler.SendMessage(message)
	rsp := <-message.ResponseChan

	httpResponse := rsp.HttpResponse
	c.JSON(httpResponse.Status, httpResponse.Body)
}
